#!/usr/bin/env bash
#
# Build unique host configurations for mesh-orange nodes
#

# Define list of 40 unique hostnames
HOSTNAMES=(bathurst bayview bloor broadview chester christie college coxwell davisville donlands dufferin dundas dupont eglinton ellesmere finch greenwood islington jane keele kennedy king kipling lawrence leslie midland museum osgoode ossington pape queen rosedale runnymede spadina summerhill union warden wilson woodbine yorkdale)

# Remove built artifacts
rm -rf output

# Build configurations for each node
hostno=0
for hostname in "${HOSTNAMES[@]}"; do
  ((hostno++))

  mkdir -p output/conf.d/$hostname output/etc/$hostname

  # Create 30-mesh-workshop.tar.gz that will be extracted into /etc
  cp -r src/etc/* output/etc/$hostname/
  find output/etc/$hostname -type f -exec awk -i inplace "{ gsub(/__HOSTNAME__/, \"$hostname\") }; { print }" {} +
  find output/etc/$hostname -type f -exec awk -i inplace "{ gsub(/__HOSTNO__/, \"$hostno\") }; { print }" {} +
  tar --create --gzip -f output/conf.d/$hostname/30-mesh-workshop.tar.gz -C output/etc/$hostname .

  # Copy sh scripts
  cp src/sh/* output/conf.d/$hostname/
done