#!/usr/bin/env bash
#
# Package assets for release
#

RELEASE_VERSION=0.1

./build

# Create directory for release assets ready to be published
rm -rf publish
mkdir publish

# Package assets in tar.gz and zip formats
tar --create --gzip -f "publish/confd-${RELEASE_VERSION}.tar.gz" -C output conf.d
cd output; zip --recurse-paths "../publish/confd-${RELEASE_VERSION}.zip" conf.d; cd ..
